# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', type: 'nfs'

# master
  config.vm.define "master" do |virtualbox|
    virtualbox.vm.hostname = "master"
    virtualbox.vm.box = "file://builds/virtualbox-centos8.box"
    virtualbox.vm.network :private_network, ip: "172.16.3.2"

    config.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 1024
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  
    config.vm.provision "ansible" do |ansible|
      ansible.playbook ="../../ansible/ansible_role_baseline.yml"
      ansible.extra_vars = { ansible_python_interpreter:"/usr/libexec/platform-python" }
    end
  end

  # node01
  config.vm.define "node01" do |virtualbox|
    virtualbox.vm.hostname = "node01"
    virtualbox.vm.box = "file://builds/virtualbox-centos8.box"
    virtualbox.vm.network :private_network, ip: "172.16.3.3"

    config.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 1024
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.provision "ansible" do |ansible|
      ansible.playbook ="../../ansible/ansible_role_baseline.yml"
      ansible.extra_vars = { ansible_python_interpreter:"/usr/libexec/platform-python" }
    end
  end

    # node02.
  config.vm.define "node02" do |virtualbox|
    virtualbox.vm.hostname = "node02"
    virtualbox.vm.box = "file://builds/virtualbox-centos8.box"
    virtualbox.vm.network :private_network, ip: "172.16.3.4"

    config.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 1024
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.provision "ansible" do |ansible|
      ansible.playbook ="../../ansible/ansible_role_baseline.yml"
      ansible.extra_vars = { ansible_python_interpreter:"/usr/libexec/platform-python" }
    end
  end

end
